/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinicmanagement.GUI;

import clinicmanagement.add.AddNewDoctor;
import clinicmanagement.add.AddNewSecretary;
import clinicmanagement.add.AddNewSection;
import clinicmanagement.commons.Commons;
import clinicmanagement.commons.TxtFileManager;
import clinicmanagement.identities.Manager;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


/**
 *
 * @author Administrator
 */
public class ManagerForm extends javax.swing.JFrame {
    
    /**
     * for add or remove an element from list we need a DefaultListModel 
     */
    
    DefaultListModel modelSec;
    DefaultListModel modelDr;
    DefaultListModel modelSecr;
    
    private TxtFileManager txtFileManagerSec;
    private TxtFileManager txtFileManagerDr;
    private TxtFileManager txtFileManagerSecr;

    /**
     * Creates new form ManagerForm
     */
    public ManagerForm() {
        modelSec = new DefaultListModel();
        modelDr = new DefaultListModel();
        modelSecr = new DefaultListModel();
        
        this.txtFileManagerSec=new TxtFileManager("Sections.txt");
        this.txtFileManagerDr=new TxtFileManager("Doctors.txt");
        this.txtFileManagerSecr = new TxtFileManager("Secretarys.txt"); 
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listSections = new javax.swing.JList<>();
        btnShowSections = new javax.swing.JButton();
        btnRemoveSection = new javax.swing.JButton();
        btnName = new javax.swing.JButton();
        btnRemoveDr = new javax.swing.JButton();
        btnShowDrs = new javax.swing.JButton();
        btnRegDr = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtDrSalary = new javax.swing.JTextField();
        txtClinicName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listDoctors = new javax.swing.JList<>();
        btnRSalary = new javax.swing.JButton();
        btnRegSection = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnRegSecr = new javax.swing.JButton();
        btnShowSecr = new javax.swing.JButton();
        btnRemoveSecr = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listSecrs = new javax.swing.JList<>();
        btnPaySalary = new javax.swing.JButton();
        btnGetSalary = new javax.swing.JButton();
        txtSalary1 = new javax.swing.JTextField();
        btnResetList = new javax.swing.JButton();
        btnPaySecrSalary = new javax.swing.JButton();
        btnGetSecrSalary = new javax.swing.JButton();
        txtSecrSalary = new javax.swing.JTextField();
        btnResetSecrList = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setBackground(new java.awt.Color(0, 102, 153));
        jLabel1.setFont(new java.awt.Font("W_yekan Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("فرم مديريت");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("W_nazanin Bold", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("بخش هاي کلينيک:");

        listSections.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listSections.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                listSectionsComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(listSections);

        btnShowSections.setFont(new java.awt.Font("W_yekan Bold", 0, 15)); // NOI18N
        btnShowSections.setText("نمايش بخش ها");
        btnShowSections.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowSectionsActionPerformed(evt);
            }
        });

        btnRemoveSection.setFont(new java.awt.Font("W_yekan Bold", 0, 15)); // NOI18N
        btnRemoveSection.setText("حذف کردن بخش");
        btnRemoveSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveSectionActionPerformed(evt);
            }
        });

        btnName.setFont(new java.awt.Font("W_yekan Bold", 0, 15)); // NOI18N
        btnName.setText("نام کلينيک");
        btnName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNameActionPerformed(evt);
            }
        });

        btnRemoveDr.setFont(new java.awt.Font("W_yekan Bold", 0, 15)); // NOI18N
        btnRemoveDr.setText("اخراج پزشک");
        btnRemoveDr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveDrActionPerformed(evt);
            }
        });

        btnShowDrs.setFont(new java.awt.Font("W_yekan Bold", 0, 15)); // NOI18N
        btnShowDrs.setText("نمايش پزشکان");
        btnShowDrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowDrsActionPerformed(evt);
            }
        });

        btnRegDr.setFont(new java.awt.Font("W_yekan Bold", 0, 15)); // NOI18N
        btnRegDr.setText("استخدام پزشک");
        btnRegDr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegDrActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("W_nazanin Bold", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("پزشکان کلينيک:");

        txtDrSalary.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));

        txtClinicName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));

        listDoctors.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listDoctors.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                listDoctorsComponentShown(evt);
            }
        });
        jScrollPane2.setViewportView(listDoctors);

        btnRSalary.setFont(new java.awt.Font("W_yekan Bold", 0, 15)); // NOI18N
        btnRSalary.setText("حقوق");
        btnRSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRSalaryActionPerformed(evt);
            }
        });

        btnRegSection.setFont(new java.awt.Font("W_yekan Bold", 0, 15)); // NOI18N
        btnRegSection.setText("ثبت بخش");
        btnRegSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegSectionActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("W_nazanin Bold", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("منشي هاي کلينيک:");

        btnRegSecr.setFont(new java.awt.Font("W_yekan Bold", 0, 15)); // NOI18N
        btnRegSecr.setText("استخدام منشي");
        btnRegSecr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegSecrActionPerformed(evt);
            }
        });

        btnShowSecr.setFont(new java.awt.Font("W_yekan Bold", 0, 15)); // NOI18N
        btnShowSecr.setText("نمايش منشي ها");
        btnShowSecr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowSecrActionPerformed(evt);
            }
        });

        btnRemoveSecr.setFont(new java.awt.Font("W_yekan Bold", 0, 15)); // NOI18N
        btnRemoveSecr.setText("اخراج منشي");
        btnRemoveSecr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveSecrActionPerformed(evt);
            }
        });

        listSecrs.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listSecrs.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                listSecrsComponentShown(evt);
            }
        });
        jScrollPane3.setViewportView(listSecrs);

        btnPaySalary.setFont(new java.awt.Font("W_yekan Bold", 0, 15)); // NOI18N
        btnPaySalary.setText("پرداخت حقوق");
        btnPaySalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaySalaryActionPerformed(evt);
            }
        });

        btnGetSalary.setFont(new java.awt.Font("W_yekan Bold", 0, 15)); // NOI18N
        btnGetSalary.setText("مقدار حقوق");
        btnGetSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetSalaryActionPerformed(evt);
            }
        });

        txtSalary1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));

        btnResetList.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnResetList.setText("Reset");
        btnResetList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetListActionPerformed(evt);
            }
        });

        btnPaySecrSalary.setFont(new java.awt.Font("W_yekan Bold", 0, 15)); // NOI18N
        btnPaySecrSalary.setText("پرداخت حقوق");
        btnPaySecrSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaySecrSalaryActionPerformed(evt);
            }
        });

        btnGetSecrSalary.setFont(new java.awt.Font("W_yekan Bold", 0, 15)); // NOI18N
        btnGetSecrSalary.setText("مقدار حقوق");
        btnGetSecrSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetSecrSalaryActionPerformed(evt);
            }
        });

        txtSecrSalary.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));

        btnResetSecrList.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnResetSecrList.setText("Reset");
        btnResetSecrList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetSecrListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSalary1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnShowDrs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRemoveDr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRegDr, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnRSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPaySalary, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnResetList)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDrSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGetSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnShowSections, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnRemoveSection))
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnRegSection, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtClinicName, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnShowSecr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnRemoveSecr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnRegSecr, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(230, 230, 230)
                                    .addComponent(btnPaySecrSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSecrSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGetSecrSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnResetSecrList))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSalary1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(btnRegDr, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnShowDrs, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRemoveDr, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPaySalary, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGetSalary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDrSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnResetList, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtClinicName, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(btnRegSecr, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnShowSecr, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRemoveSecr, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPaySecrSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSecrSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGetSecrSalary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnResetSecrList, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegSection, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnShowSections, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemoveSection, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowSectionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowSectionsActionPerformed
        
        /**
         * this button designed for show sections list
         */   
        ArrayList<String> sections = this.txtFileManagerSec.getListFromFile();
        
        String[] list = sections.toArray(new String[sections.size()]);
        
        String sec = null;
        
        for(int i = 0; i < list.length; i++) {
            
            sec = list[i];
            modelSec.addElement(sec);
        }
        
        listSections.setModel(modelSec);
    }//GEN-LAST:event_btnShowSectionsActionPerformed

    private void listSectionsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_listSectionsComponentShown
        
    }//GEN-LAST:event_listSectionsComponentShown

    private void btnNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNameActionPerformed
        
        /**
         * this button designed to show clinic name
         */
        
    }//GEN-LAST:event_btnNameActionPerformed

    private void btnRemoveSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveSectionActionPerformed
        
        /**
         * this button designed for delete a section from file sections
         */ 
            
        int selectedIndex = listSections.getSelectedIndex();
        
        if(selectedIndex != -1) {
            this.txtFileManagerSec.deleteRow(selectedIndex);
            modelSec.remove(selectedIndex);
        }
       listSections.setModel(modelSec);
        
    }//GEN-LAST:event_btnRemoveSectionActionPerformed

    private void btnRemoveDrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveDrActionPerformed
         /**
         * this button designed for delete a dr from file sections
         */ 
            
        int selectedIndex = listDoctors.getSelectedIndex();
        
        if(selectedIndex != -1) {
            this.txtFileManagerDr.deleteRow(selectedIndex);
            modelDr.remove(selectedIndex);
        }
       listDoctors.setModel(modelDr);
    }//GEN-LAST:event_btnRemoveDrActionPerformed

    private void btnShowDrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowDrsActionPerformed
        /**
         * this button designed for show doctors list
         */   
        ArrayList<String> doctors = this.txtFileManagerDr.getListFromFile();
        
        String[] list = doctors.toArray(new String[doctors.size()]);
        
        String dr = null;
        
        for(int i = 0; i < list.length; i++) {
            
            dr = list[i];
            modelDr.addElement(dr);
        }
        
        listDoctors.setModel(modelDr);
    }//GEN-LAST:event_btnShowDrsActionPerformed

    private void btnRegDrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegDrActionPerformed
        /**
         * this button designed for register a new dr
         */
        AddNewDoctor newDr = new AddNewDoctor();
        
        newDr.setVisible(true);
    }//GEN-LAST:event_btnRegDrActionPerformed

    private void listDoctorsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_listDoctorsComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_listDoctorsComponentShown

    private void btnRSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRSalaryActionPerformed

        Manager manager = new Manager();
        
        txtDrSalary.setText(Double.toString(manager.getSalary()));
    }//GEN-LAST:event_btnRSalaryActionPerformed

    private void btnRegSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegSectionActionPerformed
        
        AddNewSection newSec = new AddNewSection();
        
        newSec.setVisible(true);
    }//GEN-LAST:event_btnRegSectionActionPerformed

    private void btnRegSecrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegSecrActionPerformed
       
        /**
         * this button designed for register a new secretary
         */
        AddNewSecretary newSecr = new AddNewSecretary();
        
        newSecr.setVisible(true);
    }//GEN-LAST:event_btnRegSecrActionPerformed

    private void btnShowSecrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowSecrActionPerformed
        /**
         * this button designed for show Secretary list
         */   
        ArrayList<String> secretarys = this.txtFileManagerSecr.getListFromFile();
        
        String[] list = secretarys.toArray(new String[secretarys.size()]);
        
        String secr = null;
        
        for(int i = 0; i < list.length; i++) {
            
            secr = list[i];
            modelSecr.addElement(secr);
        }
        
        listSecrs.setModel(modelSecr);
    }//GEN-LAST:event_btnShowSecrActionPerformed

    private void btnRemoveSecrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveSecrActionPerformed
        /**
         * this button designed for delete a secretary from file secretary's
         */ 
            
        int selectedIndex = listSecrs.getSelectedIndex();
        
        if(selectedIndex != -1) {
            this.txtFileManagerSecr.deleteRow(selectedIndex);
            modelSecr.remove(selectedIndex);
        }
       listSecrs.setModel(modelSecr);
    }//GEN-LAST:event_btnRemoveSecrActionPerformed

    private void listSecrsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_listSecrsComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_listSecrsComponentShown

    private void btnPaySalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaySalaryActionPerformed
        
         /**
         * this button designed for pay doctors salary
         */
        String row = listDoctors.getSelectedValue();
        
        String str[] = row.split(Commons.SPLITTER);
        
        String drName = str[0];
        
        if(drName != null) {
            
           JOptionPane.showMessageDialog(rootPane, "Salary of Dr. " + drName + " payed");
        }
    }//GEN-LAST:event_btnPaySalaryActionPerformed

    private void btnGetSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetSalaryActionPerformed
        
         /**
         * this button designed for show amount of a doctors salary
         */ 
        
        String row = listDoctors.getSelectedValue();
        
        String str[] = row.split(Commons.SPLITTER);
        
        String amountSalary = str[3];
        
        String show = "Salary of Dr. " +str[0] + " is = " + amountSalary;
        
        if(amountSalary != null) {
            
           txtDrSalary.setText(show);
        }
        
        
    }//GEN-LAST:event_btnGetSalaryActionPerformed

    private void btnResetListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetListActionPerformed
        
        modelDr.clear();
    }//GEN-LAST:event_btnResetListActionPerformed

    private void btnPaySecrSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaySecrSalaryActionPerformed
        /**
         * this button designed for pay secretaries salary
         */
        String row = listSecrs.getSelectedValue();
        
        String str[] = row.split(Commons.SPLITTER);
        
        String secrName = str[0];
        
        if(secrName != null) {
            
           JOptionPane.showMessageDialog(rootPane, "Salary of Secretary " + secrName + " payed");
        }
    }//GEN-LAST:event_btnPaySecrSalaryActionPerformed

    private void btnGetSecrSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetSecrSalaryActionPerformed
        /**
         * this button designed for show amount of a secretaries salary
         */ 
        
        String row = listSecrs.getSelectedValue();
        
        String str[] = row.split(Commons.SPLITTER);
        
        String amountSalary = str[3];
        
        String show = "Salary of Secretary " +str[0] + " is = " + amountSalary;
        
        if(amountSalary != null) {
            
           txtSecrSalary.setText(show);
        }
    }//GEN-LAST:event_btnGetSecrSalaryActionPerformed

    private void btnResetSecrListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetSecrListActionPerformed
        modelSecr.clear();
    }//GEN-LAST:event_btnResetSecrListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGetSalary;
    private javax.swing.JButton btnGetSecrSalary;
    private javax.swing.JButton btnName;
    private javax.swing.JButton btnPaySalary;
    private javax.swing.JButton btnPaySecrSalary;
    private javax.swing.JButton btnRSalary;
    private javax.swing.JButton btnRegDr;
    private javax.swing.JButton btnRegSecr;
    private javax.swing.JButton btnRegSection;
    private javax.swing.JButton btnRemoveDr;
    private javax.swing.JButton btnRemoveSecr;
    private javax.swing.JButton btnRemoveSection;
    private javax.swing.JButton btnResetList;
    private javax.swing.JButton btnResetSecrList;
    private javax.swing.JButton btnShowDrs;
    private javax.swing.JButton btnShowSecr;
    private javax.swing.JButton btnShowSections;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listDoctors;
    private javax.swing.JList<String> listSecrs;
    private javax.swing.JList<String> listSections;
    private javax.swing.JTextField txtClinicName;
    private javax.swing.JTextField txtDrSalary;
    private javax.swing.JTextField txtSalary1;
    private javax.swing.JTextField txtSecrSalary;
    // End of variables declaration//GEN-END:variables
}
